package entities;

public enum PassengerStates {
    DISENBARKINGZONE,
    LUGGAGECOLLECTIONPOINT,
    RECLAIMOFFICE,
    ARRIALTRANSFERTERMINAL,
    TERMINALTRANSER,
    DEPARTURETRANSFERTERMINAL,
    ENTERDEPARTURETERMINAL,
    EXITARRIVALTERMINAL
}
